package zcrys.api.koth;

import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.entity.Player;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Represents an individual KOTH (King of The Hill) within the plugin.
 * This interface provides access to all KOTH information and state,
 * including configuration, current status, capture progress, and schedules.
 *
 */
public interface Koth {

    /**
     * Gets the unique name of the KOTH.
     * The name is the main identifier of the KOTH and must be unique
     * within the plugin. It may contain spaces and special characters.
     *
     * @return KOTH name
     */
    String getName();

    /**
     * Gets the unique UUID of the KOTH.
     * This identifier is internally generated by the plugin and is
     * completely unique, unlike the name which can be changed
     * by the user using the rename command.
     *
     * @return Unique UUID of the KOTH
     */
    UUID getUniqueId();

    /**
     * Gets the world where the KOTH is located.
     * The world must be loaded on the server in order to access it.
     * If the KOTH does not yet have a defined region, this method will return null.
     *
     * @return KOTH world, or null if not defined
     */
    World getWorld();

    /**
     * Gets the central location of the KOTH.
     * The center is automatically calculated as the midpoint between
     * the two corners defined for the capture area.
     *
     * @return Central location of the KOTH
     * @throws IllegalStateException if the world is not loaded or the region is not defined
     */
    Location getCenter();

    /**
     * Checks whether the KOTH is currently active.
     * An active KOTH is one that is currently running and can be captured
     * by players. Inactive KOTHs do not display bossbars and cannot be captured.
     *
     * @return true if the KOTH is active, false otherwise
     */
    boolean isActive();

    /**
     * Gets the UUID of the player currently capturing.
     * If a player is inside the zone and has started capturing,
     * this method will return their UUID. If nobody is capturing
     * or the KOTH is not active, it returns Optional.empty().
     *
     * @return Optional containing the capturer UUID, or empty if none
     */
    Optional<UUID> getCurrentCapturer();

    /**
     * Gets the name of the player currently capturing.
     * This is a more readable alternative to getCurrentCapturer()
     * when displaying the player's name in interfaces or messages.
     *
     * @return Optional containing the capturer name, or empty if none
     */
    Optional<String> getCurrentCapturerName();

    /**
     * Gets the current capture progress in seconds.
     * Represents how many seconds the current player has been
     * continuously capturing the KOTH. This value resets if the
     * capturer leaves the zone.
     *
     * @return Seconds of capture progress
     */
    int getCaptureProgress();

    /**
     * Gets the total time required to capture the KOTH.
     * This is the time in seconds a player must remain inside
     * the zone to successfully complete the capture.
     *
     * @return Total capture time in seconds
     */
    int getCaptureTime();

    /**
     * Gets the remaining time to complete the capture.
     * Calculated as: getCaptureTime() - getCaptureProgress().
     * If there is no active capturer, it returns the total time.
     *
     * @return Remaining seconds for capture
     */
    int getRemainingTime();

    /**
     * Gets the current capture percentage.
     * Calculated as: (getCaptureProgress() * 100) / getCaptureTime().
     * Returns a value between 0 and 100.
     *
     * @return Capture completion percentage
     */
    int getCapturePercentage();

    /**
     * Gets the auto-suspend time due to inactivity.
     * If there are no players in the zone for this amount of time
     * (in seconds), the KOTH will automatically suspend to save resources.
     *
     * @return Auto-suspend time in seconds
     */
    int getAutoSuspendTime();

    /**
     * Gets the configured bossbar type for this KOTH.
     * Available types:
     * <ul>
     *   <li>ANIMATED - Animated bossbar with visual effects</li>
     *   <li>MINIMALIST - Clean and minimal design</li>
     *   <li>PROGRESS_BAR - Detailed progress bar</li>
     *   <li>PARTICLES_ACTIONBAR - Actionbar with particle effects</li>
     * </ul>
     *
     * @return Configured bossbar type
     */
    String getBossbarType();

    /**
     * Gets the outline color of the player currently capturing.
     * When a player is capturing, they receive a glowing effect
     * with this color so they can be easily identified.
     * Available colors: RED, GOLD, YELLOW, GREEN, DARK_GREEN,
     * AQUA, BLUE, WHITE, GRAY, NONE (no color).
     *
     * @return Configured outline color
     */
    String getOutlineColor();

    /**
     * Checks whether particle effects are enabled for this KOTH.
     * When enabled, particles appear around the player who is
     * capturing to provide additional visual feedback.
     *
     * @return true if particle effects are enabled
     */
    boolean hasParticleDisplay();

    /**
     * Gets the configured timezone for the KOTH.
     * This timezone is used to schedule automatic starts
     * and display times correctly according to the server region.
     * Format: "Continent/City" (e.g., "America/New_York").
     *
     * @return Configured timezone
     */
    String getTimezone();

    /**
     * Checks whether auto-start is enabled for this KOTH.
     * When enabled, the KOTH will automatically start according
     * to the scheduled times on the configured days.
     *
     * @return true if auto-start is enabled
     */
    boolean isAutoStartEnabled();

    /**
     * Checks whether capture alerts are enabled.
     * Alerts notify all players when someone is about
     * to capture the KOTH (when only a few seconds remain).
     *
     * @return true if alerts are enabled
     */
    boolean isAlertEnabled();

    /**
     * Gets the alert time before capture.
     * This is the number of seconds before the capture completes
     * when alerts (titles, sounds, etc.) start appearing.
     *
     * @return Alert time in seconds
     */
    int getAlertTime();

    /**
     * Gets the configured minutes for auto-start advance alerts.
     * These minutes represent how long before the automatic start
     * alerts will be sent to players.
     * Example: [30, 15, 5] means alerts 30, 15, and 5 minutes before.
     *
     * @return List of configured alert minutes
     */
    List<Integer> getAlertMinutes();

    /**
     * Checks whether minute alerts are enabled.
     * When enabled, alerts will be sent at the minutes configured
     * in getAlertMinutes() before each automatic start.
     *
     * @return true if minute alerts are enabled
     */
    boolean isAlertMinutesEnabled();

    /**
     * Gets the scheduled times for a specific day.
     * Times are in HH:MM format (24-hour clock) and represent
     * when the KOTH will automatically start if auto-start is enabled.
     *
     * @param day Day of the week in English (MONDAY, TUESDAY, etc.)
     * @return List of times in HH:MM format
     */
    List<String> getScheduledTimes(String day);

    /**
     * Checks whether a specific day is enabled for auto-start.
     * Only enabled days will have their scheduled times executed
     * when the time arrives.
     *
     * @param day Day of the week in English (MONDAY, TUESDAY, etc.)
     * @return true if the day is enabled
     */
    boolean isDayEnabled(String day);

    /**
     * Gets the active reward slots.
     * Active slots are those that will execute when a player
     * captures the KOTH. Each slot may contain multiple commands and items.
     *
     * @return Collection of active slot numbers (20,21,22,23,24,31,39,40,41)
     */
    Collection<Integer> getActiveRewardSlots();

    /**
     * Gets the total number of rewards in a specific slot.
     * The count includes both commands and physical items
     * configured in that slot.
     *
     * @param slot Slot number to check
     * @return Total number of rewards in that slot
     */
    int getRewardCount(int slot);

    /**
     * Checks whether a specific location is inside the KOTH region.
     * Useful for determining if a player is inside the capture area
     * or verifying if a location belongs to the KOTH.
     *
     * @param location Location to check
     * @return true if the location is inside the region
     */
    boolean contains(Location location);

    /**
     * Gets the last time the KOTH was automatically started.
     * This information is useful for statistics and to know
     * when the KOTH was last active.
     *
     * @return Optional containing the last start time (HH:MM), or empty if never started
     */
    Optional<String> getLastKothTime();

    /**
     * Calculates the time until the next automatic start.
     * It analyzes today's scheduled times and, if none remain,
     * searches the following days until it finds the next start.
     *
     * @return Seconds until the next start, or -1 if none scheduled
     */
    long getTimeUntilNextStart();

    /**
     * Calculates the time elapsed since the last automatic start.
     * Useful for displaying how long it has been since the KOTH
     * was last automatically active.
     *
     * @return Seconds since the last start, or -1 if it has never started
     */
    long getTimeSinceLastStart();

    // ========== NEW METHODS (v1.2.0) ==========

    /**
     * Gets the total number of times this KOTH has been captured.
     * This statistic is tracked globally and persists across server restarts.
     *
     * @return Total captures count
     * @since 1.2.0
     */
    int getTotalCaptures();

    /**
     * Gets the total number of kills that have occurred inside this KOTH zone.
     * This statistic is tracked globally and persists across server restarts.
     *
     * @return Total kills count
     * @since 1.2.0
     */
    int getTotalKills();

    /**
     * Gets the total number of deaths that have occurred inside this KOTH zone.
     * This statistic is tracked globally and persists across server restarts.
     *
     * @return Total deaths count
     * @since 1.2.0
     */
    int getTotalDeaths();

    /**
     * Gets the total number of times this KOTH has been activated (started).
     * This includes both manual starts and automatic scheduled starts.
     *
     * @return Total activations count
     * @since 1.2.0
     */
    int getTotalActivations();

    /**
     * Gets the total time this KOTH has been active (in seconds).
     * The counter runs while the KOTH is active and stops when it's deactivated.
     *
     * @return Total active time in seconds
     * @since 1.2.0
     */
    long getTotalActiveTime();

    /**
     * Checks if clan integration is enabled for rewards distribution.
     * When enabled, rewards are given to all online clan members
     * of the capturing player. When disabled, rewards go only to
     * the capturing player.
     *
     * @return true if clan rewards are enabled
     * @since 1.2.0
     */
    boolean isClanRewardsEnabled();

    /**
     * Gets the clan tag of the player currently capturing, if any.
     * This method requires a compatible clan plugin and PlaceholderAPI.
     *
     * @return Optional containing the clan tag, or empty if no clan or integration disabled
     * @since 1.2.0
     */
    Optional<String> getCurrentCapturerClan();

    /**
     * Gets the formatted display name of the current capturer including clan tag.
     * Format is configurable in config.yml via the 'capturer-format' option.
     * Example: "[%clan%] %player%"
     *
     * @return Optional containing the formatted name, or empty if no capturer
     * @since 1.2.0
     */
    Optional<String> getCurrentCapturerDisplayName();

    /**
     * Gets all players who will receive rewards when this KOTH is captured.
     * If clan rewards are enabled, this returns all online clan members
     * of the capturing player. Otherwise, it returns just the capturing player.
     *
     * @return Collection of players who will receive rewards, or empty list if no capturer
     * @since 1.2.0
     */
    Collection<Player> getRewardRecipients();
}